(function(i,s){typeof exports=="object"&&typeof module<"u"?module.exports=s():typeof define=="function"&&define.amd?define(s):(i=typeof globalThis<"u"?globalThis:i||self,i.MyWidget=s())})(this,function(){"use strict";class i{constructor({position:e="bottom-right",containerId:t="my-widget"}){if(this.container=document.getElementById(t),!this.container){console.error(`Widget container with ID '${t}' not found.`);return}this.position=this.getPosition(e),this.open=!1,this.initialise(),this.createStyles()}getPosition(e){const[t,n]=e.split("-");return{[t]:"30px",[n]:"30px"}}initialise(){this.container.style.position="fixed",Object.keys(this.position).forEach(t=>this.container.style[t]=this.position[t]);const e=document.createElement("div");e.classList.add("talk-button-container"),this.chatIcon=document.createElement("img"),this.chatIcon.src="https://res.cloudinary.com/dg4k5afvg/image/upload/v1740582176/widget/chat_ljhqfj.svg",this.chatIcon.classList.add("talk-icon"),this.closeIcon=document.createElement("img"),this.closeIcon.src="https://res.cloudinary.com/dg4k5afvg/image/upload/v1740582176/widget/cross_mzn7tc.svg",this.closeIcon.classList.add("talk-icon","talk-hidden"),e.appendChild(this.chatIcon),e.appendChild(this.closeIcon),e.addEventListener("click",this.toggleOpen.bind(this)),this.messageContainer=document.createElement("div"),this.messageContainer.classList.add("talk-hidden","talk-message-container"),this.createMessageContainerContent(),this.container.appendChild(this.messageContainer),this.container.appendChild(e)}createMessageContainerContent(){this.messageContainer.innerHTML="";const e=document.createElement("h2");e.textContent="Send us a message";const t=document.createElement("form");t.classList.add("talk-content");const n=document.createElement("input");n.required=!0,n.id="email",n.type="email",n.placeholder="Enter your email address";const a=document.createElement("textarea");a.required=!0,a.id="message",a.placeholder="Your message";const o=document.createElement("button");o.textContent="Submit",t.appendChild(n),t.appendChild(a),t.appendChild(o),t.addEventListener("submit",this.submit.bind(this)),this.messageContainer.appendChild(e),this.messageContainer.appendChild(t)}toggleOpen(){this.open=!this.open,this.chatIcon.classList.toggle("talk-hidden",this.open),this.closeIcon.classList.toggle("talk-hidden",!this.open),this.messageContainer.classList.toggle("talk-hidden",!this.open)}submit(e){e.preventDefault(),console.log({email:e.target.querySelector("#email").value,message:e.target.querySelector("#message").value}),this.messageContainer.innerHTML='<h2>Thanks for your message.</h2><p class="talk-content">Someone will be in touch with you shortly.'}createStyles(){const e=document.createElement("style");e.innerHTML=`
            .talk-icon { cursor: pointer; width: 70%; position: absolute; top: 9px; left: 9px; transition: transform .3s ease; }
            .talk-hidden { transform: scale(0); }
            .talk-button-container { background-color: #003f88; width: 60px; height: 60px; border-radius: 50%; }
            .talk-message-container { box-shadow: 0 0 18px 8px rgba(0, 0, 0, 0.1), 0 0 32px 32px rgba(0, 0, 0, 0.08); width: 400px; right: -25px; bottom: 75px; max-height: 400px; position: absolute; transition: max-height .2s ease; font-family: Helvetica, Arial ,sans-serif; border-radius: 10px; }
            .talk-message-container.talk-hidden { max-height: 0px; }
            .talk-message-container h2 { margin: 0; padding: 20px 20px; color: #fff; background-color: #003f88; border-radius: 10px; text-align: center; }
            .talk-message-container .talk-content { margin: 20px 10px ; border: 1px solid #dbdbdb; padding: 10px; display: flex; background-color: #fff; flex-direction: column; }
            .talk-message-container form * { margin: 5px 0; }
            .talk-message-container form input { padding: 10px; }
            .talk-message-container form textarea { height: 100px; padding: 10px; }
            .talk-message-container form textarea::placeholder { font-family: Helvetica, Arial ,sans-serif; }
            .talk-message-container form button { cursor: pointer; background-color: #003f88; color: #fff; border: 0; border-radius: 4px; padding: 10px; }
            .talk-message-container form button:hover { background-color: #00509d; }
        `.replace(/^\s+|\n/gm,""),document.head.appendChild(e)}}return console.log("Widget App"),i});
